api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    collection:
        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: false
            items_per_page: 20
            client_enabled: true
            client_items_per_page: true
            items_per_page_parameter_name: "count"
